propper body

diff --git a/.github/workflows/release-tag.yml b/.github/workflows/release-tag.yml
--- a/.github/workflows/release-tag.yml
+++ b/.github/workflows/release-tag.yml
@@ -15,6 +15,23 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
+        with:
+          fetch-depth: 0  # Fetch all history for all tags and branches
+
+      - name: Get previus tag
+        id: params
+        run: |
+            PREVIOUS_TAG=$(gh release view --json tagName --jq '.tagName' || echo "fail")
+            echo "Previous Release (Base): $PREVIOUS_TAG"
+            echo "base_ref=$PREVIOUS_TAG" >> $GITHUB_OUTPUT
+
+      - name: Build Changelog
+        id: build_changelog
+        uses: mikepenz/release-changelog-builder-action@v4
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          fromTag: ${{ steps.params.outputs.base_ref }} -- change
+          toTag: ${{ github.ref_name }}
 
       - name: Create GitHub Release
         uses: softprops/action-gh-release@v2
@@ -22,5 +39,5 @@ jobs:
           tag_name:                ${{ github.ref_name }}
           prerelease:             true                    # set to true if this is a pre-release
           name:                    Release ${{ github.ref_name }}
-          generate_release_notes:  true                     # auto-builds the notes
+          body:                    ${{ steps.build_changelog.outputs.changelog }}
           token:                   ${{ secrets.GITHUB_TOKEN }}
